<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="L-BLR-15005144" name="java" tests="6" failures="5" timestamp="21 Aug 2017 13:47:33 GMT" time="0.133" errors="0">
  <testcase name="test2" time="0.034" classname="com.sakthi.project.javacodes.MultiTests">
    <failure type="java.lang.AssertionError" message="expected [Sakthi1] but found [Sakthi]">
      <![CDATA[java.lang.AssertionError: expected [Sakthi1] but found [Sakthi]
	at com.sakthi.project.javacodes.MultiTests.test2(MultiTests.java:21)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="com.sakthi.project.javacodes.MultiTests">
    <failure type="java.lang.AssertionError" message="expected [Sakthi1] but found [Sakthi]">
      <![CDATA[java.lang.AssertionError: expected [Sakthi1] but found [Sakthi]
	at com.sakthi.project.javacodes.MultiTests.test2(MultiTests.java:21)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="com.sakthi.project.javacodes.MultiTests">
    <failure type="java.lang.AssertionError" message="expected [Sakthi1] but found [Sakthi]">
      <![CDATA[java.lang.AssertionError: expected [Sakthi1] but found [Sakthi]
	at com.sakthi.project.javacodes.MultiTests.test2(MultiTests.java:21)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.004" classname="com.sakthi.project.javacodes.MultiTests">
    <failure type="java.lang.AssertionError" message="expected [Sakthi1] but found [Sakthi]">
      <![CDATA[java.lang.AssertionError: expected [Sakthi1] but found [Sakthi]
	at com.sakthi.project.javacodes.MultiTests.test2(MultiTests.java:21)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.004" classname="com.sakthi.project.javacodes.MultiTests">
    <failure type="java.lang.AssertionError" message="expected [Sakthi1] but found [Sakthi]">
      <![CDATA[java.lang.AssertionError: expected [Sakthi1] but found [Sakthi]
	at com.sakthi.project.javacodes.MultiTests.test2(MultiTests.java:21)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test6" time="0.003" classname="com.sakthi.project.javacodes.MultiTests"/>
</testsuite> <!-- java -->
